# Configuration Netlify pour déploiement automatique
[build]
  # Commande de build
  command = "npm run build"

  # Dossier de sortie (celui qui contient les fichiers buildés)
  publish = "dist"

  # Variables d'environnement pour le build
  [build.environment]
    NODE_VERSION = "18"

# Redirections pour React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les variables d'environnement
# Note: Les variables d'environnement doivent être configurées dans l'interface Netlify
# Settings > Build & deploy > Environment > Environment variables
